# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ai_service_pb2 as ai__service__pb2


class AIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectObjects = channel.unary_unary(
            "/aiservice.AIService/DetectObjects",
            request_serializer=ai__service__pb2.ImageRequest.SerializeToString,
            response_deserializer=ai__service__pb2.DetectionResponse.FromString,
        )
        self.ExtractText = channel.unary_unary(
            "/aiservice.AIService/ExtractText",
            request_serializer=ai__service__pb2.OCRRequest.SerializeToString,
            response_deserializer=ai__service__pb2.OCRResponse.FromString,
        )
        self.TranscribeAudio = channel.unary_unary(
            "/aiservice.AIService/TranscribeAudio",
            request_serializer=ai__service__pb2.AudioRequest.SerializeToString,
            response_deserializer=ai__service__pb2.transcriptionResponse.FromString,
        )
        self.VisualQuestionAnswering = channel.unary_unary(
            "/aiservice.AIService/VisualQuestionAnswering",
            request_serializer=ai__service__pb2.VQARequest.SerializeToString,
            response_deserializer=ai__service__pb2.VQAResponse.FromString,
        )


class AIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def DetectObjects(self, request, context):
        """Detects objects in an image"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExtractText(self, request, context):
        """Extracts text from an image (OCR)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TranscribeAudio(self, request, context):
        """Transcribes audio to text"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def VisualQuestionAnswering(self, request, context):
        """Visual Question Answering (VQA)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "DetectObjects": grpc.unary_unary_rpc_method_handler(
            servicer.DetectObjects,
            request_deserializer=ai__service__pb2.ImageRequest.FromString,
            response_serializer=ai__service__pb2.DetectionResponse.SerializeToString,
        ),
        "ExtractText": grpc.unary_unary_rpc_method_handler(
            servicer.ExtractText,
            request_deserializer=ai__service__pb2.OCRRequest.FromString,
            response_serializer=ai__service__pb2.OCRResponse.SerializeToString,
        ),
        "TranscribeAudio": grpc.unary_unary_rpc_method_handler(
            servicer.TranscribeAudio,
            request_deserializer=ai__service__pb2.AudioRequest.FromString,
            response_serializer=ai__service__pb2.transcriptionResponse.SerializeToString,
        ),
        "VisualQuestionAnswering": grpc.unary_unary_rpc_method_handler(
            servicer.VisualQuestionAnswering,
            request_deserializer=ai__service__pb2.VQARequest.FromString,
            response_serializer=ai__service__pb2.VQAResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "aiservice.AIService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectObjects(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aiservice.AIService/DetectObjects",
            ai__service__pb2.ImageRequest.SerializeToString,
            ai__service__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ExtractText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aiservice.AIService/ExtractText",
            ai__service__pb2.OCRRequest.SerializeToString,
            ai__service__pb2.OCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def TranscribeAudio(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aiservice.AIService/TranscribeAudio",
            ai__service__pb2.AudioRequest.SerializeToString,
            ai__service__pb2.transcriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def VisualQuestionAnswering(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aiservice.AIService/VisualQuestionAnswering",
            ai__service__pb2.VQARequest.SerializeToString,
            ai__service__pb2.VQAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
