// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/ai_service.proto

package aiservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_DetectObjects_FullMethodName           = "/aiservice.AIService/DetectObjects"
	AIService_ExtractText_FullMethodName             = "/aiservice.AIService/ExtractText"
	AIService_TranscribeAudio_FullMethodName         = "/aiservice.AIService/TranscribeAudio"
	AIService_VisualQuestionAnswering_FullMethodName = "/aiservice.AIService/VisualQuestionAnswering"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	// Detects objects in an image
	DetectObjects(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
	// Extracts text from an image (OCR)
	ExtractText(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error)
	// Transcribes audio to text
	TranscribeAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (*TranscriptionResponse, error)
	// Visual Question Answering (VQA)
	VisualQuestionAnswering(ctx context.Context, in *VQARequest, opts ...grpc.CallOption) (*VQAResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) DetectObjects(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, AIService_DetectObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ExtractText(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OCRResponse)
	err := c.cc.Invoke(ctx, AIService_ExtractText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) TranscribeAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (*TranscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscriptionResponse)
	err := c.cc.Invoke(ctx, AIService_TranscribeAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) VisualQuestionAnswering(ctx context.Context, in *VQARequest, opts ...grpc.CallOption) (*VQAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VQAResponse)
	err := c.cc.Invoke(ctx, AIService_VisualQuestionAnswering_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	// Detects objects in an image
	DetectObjects(context.Context, *ImageRequest) (*DetectionResponse, error)
	// Extracts text from an image (OCR)
	ExtractText(context.Context, *OCRRequest) (*OCRResponse, error)
	// Transcribes audio to text
	TranscribeAudio(context.Context, *AudioRequest) (*TranscriptionResponse, error)
	// Visual Question Answering (VQA)
	VisualQuestionAnswering(context.Context, *VQARequest) (*VQAResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) DetectObjects(context.Context, *ImageRequest) (*DetectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectObjects not implemented")
}
func (UnimplementedAIServiceServer) ExtractText(context.Context, *OCRRequest) (*OCRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractText not implemented")
}
func (UnimplementedAIServiceServer) TranscribeAudio(context.Context, *AudioRequest) (*TranscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TranscribeAudio not implemented")
}
func (UnimplementedAIServiceServer) VisualQuestionAnswering(context.Context, *VQARequest) (*VQAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VisualQuestionAnswering not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_DetectObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DetectObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DetectObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DetectObjects(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ExtractText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OCRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ExtractText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ExtractText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ExtractText(ctx, req.(*OCRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_TranscribeAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).TranscribeAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_TranscribeAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).TranscribeAudio(ctx, req.(*AudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_VisualQuestionAnswering_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VQARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).VisualQuestionAnswering(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_VisualQuestionAnswering_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).VisualQuestionAnswering(ctx, req.(*VQARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiservice.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectObjects",
			Handler:    _AIService_DetectObjects_Handler,
		},
		{
			MethodName: "ExtractText",
			Handler:    _AIService_ExtractText_Handler,
		},
		{
			MethodName: "TranscribeAudio",
			Handler:    _AIService_TranscribeAudio_Handler,
		},
		{
			MethodName: "VisualQuestionAnswering",
			Handler:    _AIService_VisualQuestionAnswering_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai_service.proto",
}
