// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "TemanDifa Support",
            "email": "support@temandifa.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ask": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ask a question about an image (VQA) using Google Gemini via gRPC",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "Visual Question Answering",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question about the image",
                        "name": "question",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/cache": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clear all AI-related cache entries (detection, OCR, transcription)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Clear all AI cache",
                "responses": {
                    "200": {
                        "description": "Total deleted count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/detection": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clear all object detection cache entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Clear detection cache",
                "responses": {
                    "200": {
                        "description": "Deleted count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to clear cache",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/ocr": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clear all OCR cache entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Clear OCR cache",
                "responses": {
                    "200": {
                        "description": "Deleted count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to clear cache",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Redis cache hit/miss statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Get cache statistics",
                "responses": {
                    "200": {
                        "description": "Cache statistics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/transcription": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clear all audio transcription cache entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Clear transcription cache",
                "responses": {
                    "200": {
                        "description": "Deleted count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to clear cache",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/detect": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Detect objects in an image using YOLOv8 with caching (via gRPC)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "Detect objects in image",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file (jpg, png, webp)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detection results",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "No file uploaded",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "AI Service unavailable",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get comprehensive health status of all services with latency info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_dto.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get paginated history for authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Get user history",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page (max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/temandifa-backend_internal_models.History"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/temandifa-backend_internal_helpers.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save a new history entry for authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Create history entry",
                "parameters": [
                    {
                        "description": "History data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.CreateHistoryInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/temandifa-backend_internal_models.History"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete all history entries for authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Clear all history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "deleted": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/history/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a specific history entry by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Delete history entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "History ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate user and return access/refresh token pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/temandifa-backend_internal_dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoke the current refresh token and blacklist access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "parameters": [
                    {
                        "description": "Refresh token to revoke",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout/all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoke all refresh tokens for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout from all devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ocr": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Perform OCR on an image using PaddleOCR via gRPC",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "Extract text from image (OCR)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en",
                        "description": "Language: en, id, ch",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/refresh": {
            "post": {
                "description": "Exchange refresh token for new access/refresh token pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/temandifa-backend_internal_dto.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/temandifa-backend_internal_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/temandifa-backend_internal_dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/temandifa-backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transcribe": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Convert audio to text using Whisper via gRPC",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "Transcribe audio to text",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_handlers.CreateHistoryInput": {
            "description": "History creation input",
            "type": "object",
            "required": [
                "feature_type"
            ],
            "properties": {
                "feature_type": {
                    "type": "string",
                    "enum": [
                        "OBJECT",
                        "OCR",
                        "VOICE"
                    ],
                    "example": "OBJECT"
                },
                "input_source": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "camera_capture"
                },
                "result_text": {
                    "type": "string",
                    "maxLength": 10000,
                    "example": "Detected: person, car"
                }
            }
        },
        "temandifa-backend_internal_dto.HealthCheck": {
            "type": "object",
            "properties": {
                "latency_ms": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "temandifa-backend_internal_dto.HealthResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/temandifa-backend_internal_dto.HealthCheck"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "temandifa-backend_internal_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "password": {
                    "type": "string",
                    "maxLength": 72
                }
            }
        },
        "temandifa-backend_internal_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/temandifa-backend_internal_dto.UserInfo"
                }
            }
        },
        "temandifa-backend_internal_dto.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "temandifa-backend_internal_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "full_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "temandifa-backend_internal_dto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "temandifa-backend_internal_dto.UserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "temandifa-backend_internal_dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "profile_picture": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "temandifa-backend_internal_helpers.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "temandifa-backend_internal_models.FeatureType": {
            "type": "string",
            "enum": [
                "OBJECT",
                "OCR",
                "VOICE"
            ],
            "x-enum-varnames": [
                "FeatureObject",
                "FeatureOCR",
                "FeatureVoice"
            ]
        },
        "temandifa-backend_internal_models.History": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "feature_type": {
                    "description": "OBJECT, OCR, VOICE",
                    "allOf": [
                        {
                            "$ref": "#/definitions/temandifa-backend_internal_models.FeatureType"
                        }
                    ]
                },
                "id": {
                    "type": "integer"
                },
                "input_source": {
                    "description": "URL or filename of image/audio",
                    "type": "string"
                },
                "result_text": {
                    "description": "Classification result or transcribed text",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "temandifa-backend_internal_response.ErrorCode": {
            "type": "string",
            "enum": [
                "UNAUTHORIZED",
                "INVALID_CREDENTIALS",
                "TOKEN_EXPIRED",
                "TOKEN_INVALID",
                "TOKEN_REVOKED",
                "FORBIDDEN",
                "VALIDATION_ERROR",
                "INVALID_INPUT",
                "MISSING_FIELD",
                "INVALID_FORMAT",
                "NOT_FOUND",
                "CONFLICT",
                "ALREADY_EXISTS",
                "RATE_LIMITED",
                "AI_SERVICE_UNAVAILABLE",
                "AI_SERVICE_ERROR",
                "DATABASE_ERROR",
                "CACHE_ERROR",
                "EXTERNAL_SERVICE_ERROR",
                "INTERNAL_ERROR",
                "TIMEOUT",
                "SERVICE_UNAVAILABLE",
                "FILE_TOO_LARGE",
                "INVALID_FILE_TYPE",
                "UNAUTHORIZED",
                "TOKEN_INVALID",
                "TOKEN_EXPIRED",
                "INVALID_CREDENTIALS",
                "VALIDATION_ERROR",
                "INVALID_INPUT",
                "MISSING_FIELD",
                "NOT_FOUND",
                "ALREADY_EXISTS",
                "CONFLICT",
                "RATE_LIMITED",
                "INTERNAL_ERROR",
                "SERVICE_UNAVAILABLE",
                "DATABASE_ERROR",
                "AI_SERVICE_ERROR",
                "FILE_TOO_LARGE",
                "INVALID_FILE_TYPE"
            ],
            "x-enum-varnames": [
                "ErrCodeUnauthorized",
                "ErrCodeInvalidToken",
                "ErrCodeTokenExpired",
                "ErrCodeInvalidCredentials",
                "ErrCodeValidation",
                "ErrCodeInvalidInput",
                "ErrCodeMissingField",
                "ErrCodeNotFound",
                "ErrCodeAlreadyExists",
                "ErrCodeConflict",
                "ErrCodeRateLimited",
                "ErrCodeInternal",
                "ErrCodeServiceUnavailable",
                "ErrCodeDatabaseError",
                "ErrCodeAIServiceError",
                "ErrCodeFileTooLarge",
                "ErrCodeInvalidFileType"
            ]
        },
        "temandifa-backend_internal_response.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/temandifa-backend_internal_response.ErrorCode"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "temandifa-backend_internal_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/temandifa-backend_internal_response.ErrorInfo"
                },
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "temandifa-backend_internal_response.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "meta": {},
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TemanDifa API",
	Description:      "API for TemanDifa - Assistive AI Application for the Visually Impaired",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
